name: proteinmpnn
channels:
  - conda-forge
  - bioconda
  - pytorch
  - nodefaults

dependencies:
  - python
  - ipython
  - conda-forge::pytorch # [not osx]
  - conda-forge::pytorch-gpu # [not osx]
  - pytorch::pytorch # [osx]
  - torchvision
  - torchaudio
  - cudatoolkit-dev #[linux]
  - cudatoolkit>=11.6 #[linux]
  - snakemake
  - jupyterlab
  - pandas
  - matplotlib
  - seaborn
  - numpy
  - pip
  - pip:
      - -e .
      #- git+https://github.com/gieses/ProteinMPNN.git